apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret-uri
data:
  mongo_uri: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpteU5ld1Bhc3N3b3JkQGNsdXN0ZXIwLndqaTdvZ3MubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
